modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ZsoltMolnarrr/Rogues/issues"
license = "All-Rights-Reserved"

[[mods]]
modId = "rogues"
version = "${version}"
displayName = "Rogues & Warriors (RPG Series)"
authors = "Daedelus"
description = '''
Silent Blades, Mighty Blows - Dominate with martial skills!
'''
logoFile = "icon.png"

[[dependencies.rogues]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rogues]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_compat_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rogues]]
modId = "azurelibarmor"
type = "required"
versionRange = "[${azure_lib_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rogues]]
modId = "spell_engine"
type = "required"
versionRange = "[${spell_engine_version},)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.rogues]]
modId = "structure_pool_api"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "rogues.mixins.json"
